apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint-{{ include "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels" . | nindent 4 }}
data:
  init: |
    {{- .Files.Get "files/init" | nindent 4 }} 